#!/usr/bin/env python3

import datetime
import json
import sys
import click
import phe

__author__ = 'brian'


def log(m, color='red'):
    click.echo(click.style(m, fg=color), err=True)


@click.group("pheutil")
@click.version_option('1.0-alpha')
@click.option('--verbose', '-v', is_flag=True,
              help='Enables verbose mode.')
def cli(verbose=False):
    """CLI for interacting with python-paillier
    """

@cli.command("genpkey")
@click.argument('output', type=click.File('w'))
@click.option("--keysize", type=int, default=2048,
              help="The keysize in bits. Defaults to 2048")
@click.option("--id", type=str, default=None,
              help="Add an identifying comment to the key")
def generate_keypair(keysize, id, output):
    """Generate a paillier keypair.

    Output as JWK to given output file. Use "-" to output the private key to
    stdout. See the extract command to extract the public component of the
    private key.

    Note:
        The default id TEXT includes the current time.
    """
    log("Generating a paillier keypair with keysize of {}".format(keysize))
    pub, priv = phe.generate_paillier_keypair(n_length=keysize)

    log("Keys generated")

    date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    jwk_public = {
        'kty': "PAI",
        'alg': "PAI-GN1",
        "key_ops": ["encrypt"],
        'n': phe.util.int_to_base64(pub.n),
        'kid': "Paillier public key generated by pheutil on {}".format(date)
    }

    jwk_private = {
        'kty': "PAI",
        'key_ops': ["decrypt"],
        'lambda': phe.util.int_to_base64(priv.Lambda),
        'mu': phe.util.int_to_base64(priv.mu),
        'pub': jwk_public,
        'kid': "Paillier private key generated by pheutil on {}".format(date)
    }

    json.dump(jwk_private, output)
    output.write('\n')

    log("Private key written to {}".format(output.name))


@cli.command()
@click.argument('input', type=click.File('r'))
@click.argument('output', type=click.File('w'))
def extract(input, output):
    """Given a private paillier key, as generated by generate, extract the
    public key portion.

    Use "-" to output to stdout.
    """
    log("Loading paillier keypair")
    priv = json.load(input)
    assert 'pub' in priv, "Invalid private key"
    json.dump(priv['pub'], output)
    output.write('\n')
    log("Public key written to {}".format(output.name))


def load_public_key(public_key_data):
    assert 'alg' in public_key_data
    assert public_key_data['alg'] == 'PAI-GN1'
    n = phe.util.base64_to_int(public_key_data['n'])
    pub = phe.PaillierPublicKey(n+1, n)
    return pub


@cli.command()
@click.argument('public', type=click.File('r'))
@click.argument('plaintext', type=str)
@click.option('--output', type=click.File('w'),
              help="Save to file instead of stdout")
def encrypt(public, plaintext, output=None):
    """Encrypt a floating point number with public key
    The plaintext input will be interpreted as a floating point number.

    Output will be a JSON object with a "v" attribute containing the
    ciphertext as a string, and "e" the exponent as a Number,
    fixed at -32.

    Note if you are passing a negative number to encrypt, you will
    need to include a "--" between the public key and your plaintext.
    """
    num = float(plaintext)

    log("Loading public key")
    publickeydata = json.load(public)
    pub = load_public_key(publickeydata)

    log("Encrypting: {:+.16f}".format(num))
    enc = pub.encrypt(num)
    enc = enc.decrease_exponent_to(-32)

    assert enc.exponent == -32

    # TODO #8 Decide on serialization for encrypted number...
    obj = json.dumps({
        "v": str(enc.ciphertext()),
        "e": enc.exponent
    })
    print('{}'.format(obj), file=output)


@cli.command()
@click.argument('private', type=click.File('r'))
@click.argument('ciphertext', type=click.File('r'))
@click.option('--output', type=click.File('w'),
              help="Save to file instead of stdout")
def decrypt(private, ciphertext, output):
    """Decrypt ciphertext with private key.

    """
    privatekeydata = json.load(private)
    assert 'pub' in privatekeydata
    pub = load_public_key(privatekeydata['pub'])

    log("Loading private key")

    assert 'key_ops' in privatekeydata
    assert "decrypt" in privatekeydata['key_ops']
    assert 'mu' in privatekeydata
    assert 'lambda' in privatekeydata

    _mu = phe.util.base64_to_int(privatekeydata['mu'])
    _lambda = phe.util.base64_to_int(privatekeydata['lambda'])

    priv = phe.PaillierPrivateKey(pub, _lambda, _mu)

    log("Decrypting ciphertext")
    ciphertext_data = json.load(ciphertext)
    assert ciphertext_data['e'] == -32
    enc = phe.EncryptedNumber(pub,
                              int(ciphertext_data['v']),
                              exponent=ciphertext_data['e']
                              )
    out = priv.decrypt(enc)
    print(out, file=output)

if __name__ == "__main__":
    cli()
